Add pre-commit hooks
axondeepseg/axondeepseg pull request #464
Opened 2021-02-23 18:55 UTC by vs74

This PR aims to use pre-commit hooks to limit the file size. We wish to set a limit on the file sizes so that contributors don't commit massive files in the repo. 

Fixes #423

2021-03-08 14:41 UTC, vs74 commented
This PR is ready for review. Instructions to review this PR will be added today.

2021-03-18 21:33 UTC, vs74 commented
File size of ADS repo after doing `pip install -e .` 

## models directory

103M    axondeepseg//AxonDeepSeg/models/model_seg_pns_bf
6.0M    axondeepseg//AxonDeepSeg/models/default_TEM_model/data_test
 52M    axondeepseg//AxonDeepSeg/models/default_TEM_model
928K    axondeepseg//AxonDeepSeg/models/default_SEM_model/data_test
 46M    axondeepseg//AxonDeepSeg/models/default_SEM_model
 
 ## visualization, morphometrics and data_management directory
 56K    axondeepseg//AxonDeepSeg/visualization
 56K    axondeepseg//AxonDeepSeg/data_management
 40K    axondeepseg//AxonDeepSeg/morphometrics
 
 ## docs directory
  0B    axondeepseg//docs/source/_templates
6.7M    axondeepseg//docs/source/_static
6.7M    axondeepseg//docs/source
6.7M    axondeepseg//docs

2021-03-19 22:36 UTC, vs74 commented
## Notebook directory after executing all the cells of the notebooks
```

8.0K    notebooks/03-performance_metrics.ipynb
8.0K    notebooks/04-morphometrics_extraction.ipynb
24K     notebooks/02-training_guideline.ipynb
40K     notebooks/01-guide_dataset_building.ipynb
1.5M    notebooks/00-getting_started.ipynb
```

## Notebook directory with no outputs 
```
8.0K    notebooks/03-performance_metrics.ipynb
8.0K    notebooks/04-morphometrics_extraction.ipynb
 12K    notebooks/00-getting_started.ipynb
  16K    notebooks/01-guide_dataset_building.ipynb
 24K    notebooks/02-training_guideline.ipynb
```

## Test directory

<summary>
<details>

```4.0K    test/__pycache__/test_download_models.cpython-37-PYTEST.pyc
4.0K    test/__pycache__/test_download_tests.cpython-37-PYTEST.pyc
4.0K    test/__pycache__/test_integrity_test.cpython-37-PYTEST.pyc
4.0K    test/__pycache__/test_params.cpython-37-PYTEST.pyc
4.0K    test/__test_files__/__test_16b_file__/raw/data1/pixel_size_in_micrometer.txt
4.0K    test/__test_files__/__test_demo_files__/pixel_size_in_micrometer.txt
4.0K    test/__test_files__/__test_model__/Model/checkpoint
4.0K    test/__test_files__/__test_model__/Model/config_network.json
4.0K    test/__test_files__/__test_model__/Model/evolution.pkl
4.0K    test/__test_files__/__test_model__/Model/evolution_stats.pkl
4.0K    test/__test_files__/__test_model__/Model/model.ckpt.index
4.0K    test/__test_files__/__test_model__/Model/report.txt
4.0K    test/__test_files__/__test_patch_files__/raw/data1/pixel_size_in_micrometer.txt
4.0K    test/__test_files__/__test_patch_files__/raw/data2/pixel_size_in_micrometer.txt
4.0K    test/__test_files__/__test_postprocessing_files__/after_flood_fill.png
4.0K    test/__test_files__/__test_postprocessing_files__/before_flood_fill.png
4.0K    test/__test_files__/__test_postprocessing_files__/test_numbers_image.png
4.0K    test/__test_files__/__test_segment_files_with_pixel_size__/pixel_size_in_micrometer.txt
4.0K    test/__test_files__/__test_simulated_axons__/pixel_size_in_micrometer.txt
4.0K    test/__test_files__/__test_training_files__/Testing/data1/pixel_size_in_micrometer.txt
4.0K    test/data_management/__pycache__/test_patch_extraction.cpython-37-PYTEST.pyc
4.0K    test/data_management/test_patch_extraction.py
4.0K    test/models
4.0K    test/models/test_download_models.py
4.0K    test/morphometrics/__pycache__/test_launch_morphometrics_computation.cpython-37-PYTEST.pyc
4.0K    test/morphometrics/test_launch_morphometrics_computation.py
4.0K    test/test_ads_utils.py
4.0K    test/test_download_tests.py
4.0K    test/test_integrity_test.py
4.0K    test/test_params.py
4.0K    test/test_postprocessing.py
4.0K    test/testing/__pycache__/test_launch_performance_metrics.cpython-37-PYTEST.pyc
4.0K    test/testing/test_launch_performance_metrics.py
4.0K    test/testing/test_noise_simulation.py
4.0K    test/testing/test_statistics_generation.py
4.0K    test/visualization/__pycache__/test_generate_axons_from_myelin.cpython-37-PYTEST.pyc
4.0K    test/visualization/__pycache__/test_merge_masks.cpython-37-PYTEST.pyc
4.0K    test/visualization/__pycache__/test_visualize.cpython-37-PYTEST.pyc
4.0K    test/visualization/test_generate_axons_from_myelin.py
4.0K    test/visualization/test_get_masks.py
4.0K    test/visualization/test_merge_masks.py
4.0K    test/visualization/test_visualize.py
8.0K    test/__pycache__/test_postprocessing.cpython-37-PYTEST.pyc
8.0K    test/__pycache__/test_train_network.cpython-37-PYTEST.pyc
8.0K    test/__test_files__/__test_simulated_axons__/SimulatedAxons.png
8.0K    test/__test_files__/__test_training_files__/.DS_Store
8.0K    test/test_config_tools.py
8.0K    test/test_train_network.py
8.0K    test/testing/__pycache__/test_noise_simulation.cpython-37-PYTEST.pyc
8.0K    test/testing/__pycache__/test_statistics_generation.cpython-37-PYTEST.pyc
8.0K    test/testing/test_segmentation_scoring.py
8.0K    test/visualization/__pycache__/test_get_masks.cpython-37-PYTEST.pyc
8.0K    test/visualization/test_simulate_axons.py
 12K    test/__pycache__/test_ads_utils.cpython-37-PYTEST.pyc
 12K    test/__pycache__/test_config_tools.cpython-37-PYTEST.pyc
 12K    test/__test_files__/.DS_Store
 12K    test/__test_files__/__test_postprocessing_files__
 12K    test/__test_files__/__test_simulated_axons__
 12K    test/data_management/test_dataset_building.py
 12K    test/morphometrics/test_compute_morphometrics.py
 12K    test/test_segment.py
 16K    test/__test_files__/__test_training_files__/Train/mask_0.png
 16K    test/__test_files__/__test_training_files__/Train/mask_1.png
 16K    test/__test_files__/__test_training_files__/Validation/mask_0.png
 16K    test/__test_files__/__test_training_files__/Validation/mask_1.png
 16K    test/visualization/__pycache__/test_simulate_axons.cpython-37-PYTEST.pyc
 20K    test/__test_files__/__test_patch_files__/raw/data2/mask.png
 20K    test/__test_files__/__test_training_files__/Testing/data1/mask.png
 20K    test/data_management/__pycache__/test_dataset_building.cpython-37-PYTEST.pyc
 20K    test/morphometrics/__pycache__/test_compute_morphometrics.cpython-37-PYTEST.pyc
 20K    test/testing/__pycache__/test_segmentation_scoring.cpython-37-PYTEST.pyc
 24K    test/__pycache__/test_segment.cpython-37-PYTEST.pyc
 24K    test/__test_files__/__test_model__/Model/model.ckpt.data-00000-of-00001
 24K    test/data_management/__pycache__
 24K    test/morphometrics/__pycache__
 28K    test/__test_files__/__test_demo_files__/image_seg-axon.png
 36K    test/visualization/__pycache__
 40K    test/data_management
 40K    test/morphometrics
 40K    test/testing/__pycache__
 44K    test/__test_files__/__test_training_files__/Train/image_0.png
 44K    test/__test_files__/__test_training_files__/Train/image_1.png
 44K    test/__test_files__/__test_training_files__/Validation/image_0.png
 44K    test/__test_files__/__test_training_files__/Validation/image_1.png
 48K    test/__test_files__/__test_demo_files__/image_seg-myelin.png
 60K    test/__test_files__/__test_demo_files__/__prediction_only__
 60K    test/__test_files__/__test_demo_files__/__prediction_only__/image_seg-axonmyelin.png
 60K    test/__test_files__/__test_demo_files__/image_seg-axonmyelin.png
 60K    test/testing
 60K    test/visualization
 80K    test/__pycache__
 80K    test/__test_files__/__test_demo_files__/mask.png
 80K    test/__test_files__/__test_patch_files__/raw/data1/mask.png
120K    test/__test_files__/__test_training_files__/Train
120K    test/__test_files__/__test_training_files__/Validation
224K    test/__test_files__/__test_patch_files__/raw/data2/image.png
224K    test/__test_files__/__test_segment_files__/image.png
224K    test/__test_files__/__test_segment_files__/image_2.png
224K    test/__test_files__/__test_segment_files_with_pixel_size__/image.png
224K    test/__test_files__/__test_segment_files_with_pixel_size__/image_2.png
224K    test/__test_files__/__test_training_files__/Testing/data1/image.png
248K    test/__test_files__/__test_patch_files__/raw/data2
248K    test/__test_files__/__test_training_files__/Testing
248K    test/__test_files__/__test_training_files__/Testing/data1
448K    test/__test_files__/__test_segment_files__
452K    test/__test_files__/__test_segment_files_with_pixel_size__
496K    test/__test_files__/__test_training_files__
892K    test/__test_files__/__test_demo_files__/image.png
892K    test/__test_files__/__test_patch_files__/raw/data1/image.png
976K    test/__test_files__/__test_patch_files__/raw/data1
1.0M    test/__test_files__/__test_model__/Model/model.ckpt.meta
1.1M    test/__test_files__/__test_demo_files__
1.1M    test/__test_files__/__test_model__
1.1M    test/__test_files__/__test_model__/Model
1.2M    test/__test_files__/__test_patch_files__
1.2M    test/__test_files__/__test_patch_files__/raw
8.4M    test/__test_files__/__test_16b_file__/raw/data1/image.tif
8.4M    test/__test_files__/__test_16b_file__/raw/data1/mask.tif
 17M    test/__test_files__/__test_16b_file__
 17 [...]

2021-03-20 20:17 UTC, mathieuboudreau commented
Why is the additionnal installation step `pre-commit install` needed? Is there no way to do this within the `pip install -e .` (step when installing setup.py)? Does this mean if someone forgets to do this manual step, the pre-commit hooks won't work and the user will in fact be able to push large files accidentally?

2021-03-20 20:18 UTC, mathieuboudreau commented
Since we don't ever merge to master without doing a pull request, and pull requests are squashed, wouldn't we also want a pull request check for large files (fail = can't merge)? Surely there's already some git app/tool to do this?

2021-03-20 20:29 UTC, mathieuboudreau commented
Weird behaviour, for some reason the pre-commit hook modified the file? 
<img width="805" alt="Capture d’écran 2021-03-20 à 17 59 26" src="https://user-images.githubusercontent.com/1421029/111884663-0a944e00-89a6-11eb-8fcc-5373882fd82f.png">

2021-03-20 20:33 UTC, mathieuboudreau commented
Not sure how to test **4.3** in your first post; won't it fail because of 4.1? And if 4.3 worked, wouldn't mean that 4.1 should pass? Is that why my notebook was modified above? If so, why'd it still fail?

2021-03-20 20:37 UTC, vs74 commented
> Weird behaviour, for some reason the pre-commit hook modified the file?

Yes, the pre-commit hook for the notebook will modify the file incase the notebook cells contains some output. It will clear the output of the cells. That's why the file was modified. 

So, after the file has been modified by the pre-commit hook, you can commit the changes of the modified file ( which contain changes that are nothing but the same notebook with outputs being cleared out) to push into the repo.

2021-03-20 20:41 UTC, jcohenadad commented
> Why is the additionnal installation step pre-commit install needed? Is there no way to do this within the pip install -e . (step when installing setup.py)? Does this mean if someone forgets to do this manual step, the pre-commit hooks won't work and the user will in fact be able to push large files accidentally?

> Since we don't ever merge to master without doing a pull request, and pull requests are squashed, wouldn't we also want a pull request check for large files (fail = can't merge)? Surely there's already some git app/tool to do this?

these questions were covered in the long discussion threads involving @joshuacwnewton @ahill187 @kousu @gisellemartel so I let them chip in and cross-referencing the relevant discussion points 🙏

2021-03-20 20:41 UTC, vs74 commented
> Since we don't ever merge to master without doing a pull request, and pull requests are squashed, wouldn't we also want a pull request check for large files (fail = can't merge)? Surely there's already some git app/tool to do this?

I've included the pre-commit hooks for the Travis CI as well ( see modified [.travis.yml](https://github.com/neuropoly/axondeepseg/blob/vs/pre-commit_file_size/.travis.yml) file ).  So when any of the checks fails, the build will fail. 

The current builds are failing; I will look at them and do a quick fix for them.

2021-03-20 21:00 UTC, mathieuboudreau commented
> > Weird behaviour, for some reason the pre-commit hook modified the file?
> 
> Yes, the pre-commit hook for the notebook will modify the file incase the notebook cells contains some output. It will clear the output of the cells. That's why the file was modified.
> 
> So, after the file has been modified by the pre-commit hook, you can commit the changes of the modified file ( which contain changes that are nothing but the same notebook with outputs being cleared out) to push into the repo.

Is there an option to inform the user of why the notebook is being changed? I wasn't aware the first time the hook ran, so I wasn't sure what was changed in the file because of it.

2021-03-20 21:01 UTC, mathieuboudreau commented
Woops, I wanted to delete a draft I was writing but instead clicked close with comment instead - my bad

2021-03-20 21:12 UTC, vs74 commented
> Why is the additionnal installation step `pre-commit install` needed? 

The pre-commit install step is a mandatory step for contributors/developers (see [here](https://github.com/neuropoly/axondeepseg/blob/77efacd06233257615b154ac33d9c14891cc117a/CONTRIBUTING.rst#L173)) which install the pre-commit hooks under `.git/hooks` directory. That's why this step is needed

> Is there no way to do this within the `pip install -e .` (step when installing setup.py)? 

There could be other ways too. I followed the implementation of other sister projects (**ivadomed** and **shimming-toolbox**) about pre-commit hooks and their they recommend to run `pre-commit install` first, so for consistency across the projects, I followed the same practice.

But I agree with you @mathieuboudreau that it would be better to have it pre-installed rather than manually doing pre-commit install each time a contributor/developer makes changes. We could perhaps get better insights into this decision once we hear from others.


> Does this mean if someone forgets to do this manual step, the pre-commit hooks won't work and the user will in fact be able to push large files accidentally?

Yes, in case we forget to do this step, pre-commit won't work, but it will be eventually caught in the PR build.

2021-03-20 21:40 UTC, vs74 commented
For reference about the file size of the notebook before and after executing you can take a look at this [comment](https://github.com/neuropoly/axondeepseg/pull/464#issuecomment-803172424).


> Not sure how to test **4.3** in your first post; won't it fail because of 4.1?

**4.1**  does a mere check on `file_size > 500 KB` before committing them. It adds a check on not only notebooks but also be it models and other fat files as well. 

Now, this check would fail only for the notebook (  [00-getting_started.ipynb](https://github.com/neuropoly/axondeepseg/blob/master/notebooks/00-getting_started.ipynb) as the file size is 1.5 MB after executing all the cells). For other notebook files it would pass because the file size is less even after executing all the cells. 

We discussed this in the last ADS meeting about reducing the limit on file size to 100KB or less than that. But that also wouldn't serve the purpose because the file sizes of other notebooks are at most `64KB ` even after the notebook contains all the output. Going below 100KB doesn't make sense according to me as there are some files that are 80KB or so.

Even the` 100KB` limit is too strict. So, that's why I decided to keep the limit as `500KB` and include 4.3  as an additional check on which will clear the outputs of the notebooks in case **4.1** passes but the notebooks have some outputs.


> And if 4.3 worked, wouldn't mean that 4.1 should pass?

For notebooks only, if **4.3** worked, then file size check via **4.1** would definitely pass. But what if we commit model binaries or other fat files, then 4.1 shouldn't pass right?

2021-03-20 23:27 UTC, mathieuboudreau requested changes
Thanks for clarifying everything @vs74 ! Every feature worked as expected when I tested it (now that I know what the expected behaviours were). All that's missing now is the changes required to make the tests pass; once that's done I'll approve and merge.

2021-03-21 07:37 UTC, vs74 commented
Thanks, @mathieuboudreau for testing this PR. I've resolved the issue which caused the PR build to fail. I would perhaps wait for the answers to some of the questions you asked which were discussed in ivadomed as pointed out by Julien before merging this PR.

2021-03-21 16:25 UTC, joshuacwnewton commented
>  Is there no way to do this within the `pip install -e .` (step when installing setup.py)?

Just popping in to say that `setuptools` does indeed support [post-install](https://stackoverflow.com/a/36902139) steps for editable (`-e`) mode.

2021-03-22 14:11 UTC, vs74 commented
Since with this PR #479, we are migrating to GH Actions from Travis CI. So, this PR would require some changes on GH Actions part for pre-commit hooks, in case PR #479 is merged first. Either this PR needs to merge first, so we make necessary changes in PR #479 or PR #479 needs to merged first and required changes can be made in this PR.

We need to prioritize which PR needs to merge first.

2021-03-22 14:18 UTC, mathieuboudreau commented
My opinion would be the #479 is more urgent, as delaying that one means more costs (in terms of real money, to pay for Travis credits).

2021-04-01 11:49 UTC, vs74 commented
@mathieuboudreau shall we add `pre-commit install` in [setup.py](https://github.com/neuropoly/axondeepseg/blob/master/setup.py) script as Joshua suggested (see [here](https://github.com/neuropoly/axondeepseg/pull/464#issuecomment-803615505))? 

This way we can enforce the pre-commit hooks checks are being done locally while one commits in the repo. Although the checks would get caught in the Github CI eventually even if the contributor forgets to do `pre-commit install`. 

What are your thoughts on this?

2021-04-01 15:18 UTC, vs74 commented
This PR is ready for review.

2021-04-15 14:26 UTC, vs74 commented
Seems like the installing pre-commit as a post-install option wasn't explored by the other projects ( see [here](https://github.com/shimming-toolbox/shimming-toolbox/pull/215#issuecomment-819808516) ). 


In my opinion, we should install `pre-commit ` via **setuptools** (in setup.py build script)  because as developer might forget doing this and this would prevent the checks from being skipped locally.

I've updated this PR accordingly and this PR is ready for review now.

2021-05-17 18:50 UTC, vs74 commented
@mathieuboudreau this PR is also up for review.

2021-06-03 03:29 UTC, mathieuboudreau requested changes
Umm something seems to not be working correctly, as I've just been able to both commit and push a large file (>500kb) after checking out and installing this branch. Please fix that pre-commiti hook behaviour and/or installation of it.

2021-06-03 04:27 UTC, vs74 commented
> Umm something seems to not be working correctly, as I've just been able to both commit and push a large file (>500kb) after checking out and installing this branch. Please fix that pre-commit hook behaviour and/or installation of it.

I'll look into this.

2021-06-03 06:30 UTC, vs74 commented
There was some typo in the instruction, I've fixed it. Can you follow the installation instructions by referring https://github.com/neuropoly/axondeepseg/pull/464#issue-578680738 and let me know how it goes?

I tested it locally and I wasn't able to commit **files > 500 KB**
![image](https://user-images.githubusercontent.com/31419210/120597797-1d75d500-c463-11eb-8165-7a0dd557d04d.png)

2022-07-07 16:54 UTC, mathieuboudreau commented
Ok, so here's a summary:

## Updates I've made

Very little. Handled the conflicts that were preventing a merge of master, and added a gitignore for log files that we should have done in another PR

## Purpose of this PR

Adds both a pre-commit hook (locally) and a PR check (on GitHub) for the following three things:

1. Large files greater than 500kb are prevented from being committed.
2. YAML files syntax check: ensures the proper syntax is used in each YAML files.
3. Jupyter notebook output clear check: ensures that Jupyter notebooks are cleared before commiting

## How to test

Pull branch, run `conda env update --name ads_venv --file environment.yml` to install the new dependency, and then run `pip install -e .` to install the setup file. Then,

1. Create or add a file greater than 500kb to the repo (I used `mkfile 1M test_1megabyte.txt                          ` on my mac), git add it, then try to commit it. It should fail with a message explaining why it fails.
2. Open one of our *.yml or *.yaml and write some giberish on a new line. git add it, then try to commit it. It should fail with a message explaining why it fails.
3. Open one of our juypiter notebook, run it and save. git add it, then try to commit it. It should fail with a message explaining why it fails. It should also have automatically cleared the run of the notebook and saved it, so if you git add it again, you should now be able to commit it.

If desired, you can also do one or all three directly on GitHub (eg write in a yaml file) and commit it. Here, the PR status test should fail I believe.

## Decision

I've done the tests above, and to me they worked locally. The decision now if it works for the reviewer as well is, do we actually still want this feature? It should be good to have I think. Note that every time you commit locally, you'll have the following message or a variation of it:

<img width="846" alt="Screen Shot 2022-07-07 at 1 54 40 PM" src="https://user-images.githubusercontent.com/1421029/177828620-08753c04-424d-49cb-b987-cc97c4783ca6.png">

2022-07-07 18:17 UTC, hermancollin commented
I gotta say I tried the feature but I don't know how the github workflows YAML files work.
And it doesn't work on my side:
```
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/herman/.conda/envs/ads_venv/bin/python', '-mvirtualenv', '/home/herman/.cache/pre-commit/repo2f3z2owo/py_env-python3.8')
return code: 1
expected return code: 0
stdout:
    AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsArmFramework'
    
stderr:
    /home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    
Check the log at /home/herman/.cache/pre-commit/pre-commit.log
```
But if the commit is clean (e.g. only a text file with 2-3 words inside), this error still happens. Even the integrity test script fails now:
<details>

```
Traceback (most recent call last):
  File "/home/herman/.conda/envs/ads_venv/bin/axondeepseg_test", line 33, in <module>
    sys.exit(load_entry_point('AxonDeepSeg', 'console_scripts', 'axondeepseg_test')())
  File "/home/herman/.conda/envs/ads_venv/bin/axondeepseg_test", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/herman/Documents/NEUROPOLY_21/axondeepseg/AxonDeepSeg/integrity_test.py", line 13, in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
  File "/home/herman/Documents/NEUROPOLY_21/axondeepseg/AxonDeepSeg/apply_model.py", line 8, in <module>
    from ivadomed import inference as imed_inference
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/ivadomed/inference.py", line 15, in <module>
    from ivadomed.loader.mri3d_subvolume_segmentation_dataset import MRI3DSubVolumeSegmentationDataset
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/ivadomed/loader/mri3d_subvolume_segmentation_dataset.py", line 8, in <module>
    from ivadomed import transforms as imed_transforms, postprocessing as imed_postpro
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/ivadomed/transforms.py", line 17, in <module>
    import torchio as tio
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/__init__.py", line 10, in <module>
    from .transforms import *  # noqa: F401, F403
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/transforms/__init__.py", line 1, in <module>
    from .transform import Transform
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/transforms/transform.py", line 13, in <module>
    from ..data.subject import Subject
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/data/__init__.py", line 1, in <module>
    from .queue import Queue
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/data/queue.py", line 10, in <module>
    from .sampler import PatchSampler
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/data/sampler/__init__.py", line 2, in <module>
    from .label import LabelSampler
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/data/sampler/label.py", line 14, in <module>
    class LabelSampler(WeightedSampler):
  File "/home/herman/.conda/envs/ads_venv/lib/python3.8/site-packages/torchio/data/sampler/label.py", line 109, in LabelSampler
    patch_size: npt.NDArray[np.uint],
AttributeError: module 'numpy.typing' has no attribute 'NDArray'
```
</details>

> The decision now if it works for the reviewer as well is, do we actually still want this feature? It should be good to have I think.

This feature encourages small commits. I guess it's not a bad idea.

2022-07-07 18:31 UTC, mathieuboudreau commented
Thanks for the feedback @hermancollin ! Strange that it all worked for me "out of the box" but you're encountering severe problems. It seems that it might be related to your `virtualenv` installation, which the commit hook is using to do its tests: https://exerror.com/attributeerror-module-virtualenv-create-via_global_ref-builtin-cpython-mac_os-has-no-attribute-cpython2macosarmframework/

Tbh, if this setup causes to many developer roadblocks, I'm willing to let it go. Maybe we could get a few different developers (especially the new ones in the group) to test it and if more of them have problems with the feature, then just scrap it.

2022-07-08 16:35 UTC, mathieuboudreau commented
After discussing it, we've come to the decision to not integrate this change into ADS as it is low priority that has a high risk of causing some issues, per Armand's experience. We'll not delete the branch, in case we change our minds in the future.

2022-07-08 16:35 UTC, closed without merging

2022-07-11 00:38 UTC, mathieuboudreau commented
Glad this feature won't be implemented, because now I'm getting an `/Users/mathieuboudreau/opt/anaconda3/envs/ads_venv/bin/python: No module named pre_commit` error when trying to commit in other branches, even with the env deactivated, so yeah it's still causing me headaches beyond the grave.

2022-07-11 00:39 UTC, mathieuboudreau commented
Getting ``pre-commit` not found.  Did you forget to activate your virtualenv?` now even after I deleted my old env.